/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.donniehardin.a1_q4;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 *
 * @author donnie
 */
public class Csc_230_a1_q4_rework_mainTest {
    
    public Csc_230_a1_q4_rework_mainTest() {
    }
    
    @BeforeClass
    public static void setUpClass() {
    }
    
    @AfterClass
    public static void tearDownClass() {
    }
    
    @Before
    public void setUp() {
    }
    
    @After
    public void tearDown() {
    }

    /**
     * 
     * DEFAULT: GENERATED BY NETBEANS. COMMENTING OUT.
     * 
     * Test of realChecker method, of class Csc_230_a1_q4_rework_main.
    
    @Test
    public void testRealChecker() {
        System.out.println("realChecker");
        int a = 0;
        int b = 0;
        int c = 0;
        int expResult = 0;
        int result = Csc_230_a1_q4_rework_main.realChecker(a, b, c);
        assertEquals(expResult, result);
        // TODO review the generated test code and remove the default call to fail.
        fail("The test case is a prototype.");
    }
    
    **/
    
    /* 
    Another Test of realChecker method, of class Csc_230_a1_q4_rework_main.
    */
    
    @Test
    public void testRealChecker1() {
        System.out.println("realChecker");
        int a = 1;
        int b = 2;
        int c = 3;
        Csc_230_a1_q4_rework_main instance = new Csc_230_a1_q4_rework_main();
        int expResult = 1;
        int result = instance.realChecker(a, b, c);
        assertEquals(expResult, result);
    }

    /**
     * 
     * DEFAULT: GENERATED BY NETBEANS. COMMENTING OUT.
     * 
     * Test of posSolver method, of class Csc_230_a1_q4_rework_main.
     
    @Test
    public void testPosSolver() {
        System.out.println("posSolver");
        int a = 0;
        int b = 0;
        int c = 0;
        int expResult = 0;
        int result = Csc_230_a1_q4_rework_main.posSolver(a, b, c);
        assertEquals(expResult, result);
        // TODO review the generated test code and remove the default call to fail.
        fail("The test case is a prototype.");
    }
    
    */

    @Test
    public void testPosSolver1() {
        System.out.println("posSolver");
        int a = 1;
        int b = 2;
        int c = 3;
        Csc_230_a1_q4_rework_main instance = new Csc_230_a1_q4_rework_main();        
        int expResult = 6;
        double result = instance.posSolver(a, b, c);
        assertEquals(expResult, result);
    }
    
    /**
     * 
     * DEFAULT: GENERATED BY NETBEANS. COMMENTING OUT.
     * 
     * Test of negSolver method, of class Csc_230_a1_q4_rework_main.
     
    @Test
    public void testNegSolver() {
        System.out.println("negSolver");
        int a = 0;
        int b = 0;
        int c = 0;
        int expResult = 0;
        int result = Csc_230_a1_q4_rework_main.negSolver(a, b, c);
        assertEquals(expResult, result);
        // TODO review the generated test code and remove the default call to fail.
        fail("The test case is a prototype.");
    }
    */

    @Test
    public void testNegSolver1() {
        System.out.println("negSolver");
        int a = 1;
        int b = 2;
        int c = 3;
        Csc_230_a1_q4_rework_main instance = new Csc_230_a1_q4_rework_main();        
        int expResult = -4;
        double result = instance.negSolver(a, b, c);
        assertEquals(expResult, result);
    }

    /**
     * Test of main method, of class Csc_230_a1_q4_rework_main.
     */
    
    /*
    
    I haven't figured out the best way to test Main or void methods.
    I have just commented out the default call to fail.
    */
    
    
    @Test
    public void testMain() {
        System.out.println("main");
        String[] args = null;
        Csc_230_a1_q4_rework_main.main(args);
        // TODO review the generated test code and remove the default call to fail.
        //fail("The test case is a prototype.");
    }

    /**
     * Test of realChecker method, of class Csc_230_a1_q4_rework_main.
     */
    @Test
    public void testRealChecker() {
        System.out.println("realChecker");
        int a = 0;
        int b = 0;
        int c = 0;
        int expResult = 0;
        int result = Csc_230_a1_q4_rework_main.realChecker(a, b, c);
        assertEquals(expResult, result);
        // TODO review the generated test code and remove the default call to fail.
        fail("The test case is a prototype.");
    }

    /**
     * Test of posSolver method, of class Csc_230_a1_q4_rework_main.
     */
    @Test
    public void testPosSolver() {
        System.out.println("posSolver");
        int a = 0;
        int b = 0;
        int c = 0;
        double expResult = 0.0;
        double result = Csc_230_a1_q4_rework_main.posSolver(a, b, c);
        assertEquals(expResult, result, 0.0);
        // TODO review the generated test code and remove the default call to fail.
        fail("The test case is a prototype.");
    }

    /**
     * Test of negSolver method, of class Csc_230_a1_q4_rework_main.
     */
    @Test
    public void testNegSolver() {
        System.out.println("negSolver");
        int a = 0;
        int b = 0;
        int c = 0;
        double expResult = 0.0;
        double result = Csc_230_a1_q4_rework_main.negSolver(a, b, c);
        assertEquals(expResult, result, 0.0);
        // TODO review the generated test code and remove the default call to fail.
        fail("The test case is a prototype.");
    }
    
}
